spring:
  application:
    name: tasker


  datasource:
    url: jdbc:h2:mem:taskerdb
    driver-class-name: org.h2.Driver
    username: chinmay
    password: MyDatabase@123


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


server:
  port: 4000